

services:
  # web_server:
  #   container_name: nginx_web
  #   build: 
  #     context: ./client/
  #     dockerfile: Dockerfile
  #   volumes:
  #     - ./nginx/nginx.conf:/etc/nginx/nginx.conf
  #     # - ./client/dist:/usr/share/nginx/html
  #   ports:
  #     - "80:80"
  #   networks:
  #     - poppoo_network
  #   depends_on:
  #     - postgres
  #     - web_service
  #   restart: always

  # web_service:
  #   container_name: web_service
  #   build: 
  #     context: ./server/
  #     dockerfile: Dockerfile
  #   ports:
  #     - "3000:3000"
  #   networks:
  #     - poppoo_network
  #   depends_on:
  #     - postgres
  #   working_dir: /usr/src/app
  #   restart: always
  #   command: ["/usr/src/app/setup.sh", "postgres_poppoo", "5432"]

  postgres:
    container_name: postgres_poppoo
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-postgres}
      PGDATA: /data/postgres
    volumes:
      - ./postgres:/data/postgres
    ports:
      - "6435:5432"
    networks:
      - poppoo_network
    restart: always

networks:
  poppoo_network:
    driver: bridge
