
networks:
  postgres_net:
    driver: bridge

services:
  postgres:
    container_name: postgres_snake
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-postgres}
      PGDATA: /data/postgres
    volumes:
      - ./postgres:/data/postgres
    ports:
      - "6435:5432"
    networks:
      - postgres_net
    restart: always

  # server:
  #   container_name: bun
  #   image: oven/bun:latest
  #   volumes:
  #     - ./server:/app
  #   ports:
  #     - "3001:3000"
  #   networks:
  #     - postgres_net
  #   depends_on:
  #     - postgres
  #   working_dir: /app
  #   restart: always
  #   command: bun run dev